name: Paso 6
run-name: ${{ github.actor }} acaba de hacer algo
on: [pull_request, push]
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - run: sh other/execute-me.sh
      - run: python execute-me.py
