name: Paso 6
run-name: ${{ github.actor }} acaba de hacer algo
on: [pull_request, push]
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Execute bash script
        run: bash other/execute-me.sh
      - name: Execute Python script
        run: python execute-me.py
